(package "org-node-graph"
         "0.0.1"
         "org node graph")

(website-url "")
(keywords "")

(package-file "org-graph.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "28.2")
(depends-on "dash" "2.17.0")
(depends-on "org" "9.6")
(depends-on "ov" "0")
(depends-on "s" "0")
(depends-on "plz" "0")

(development
 (depends-on "undercover")
 (depends-on "buttercup")
 (depends-on "elsa")
 (depends-on "lsp-mode"))
